export const Color = {
  BG_COLOR: '#FFFFFF',
  WHITE: '#FFFFFF',
  PRIMARY_COLOR: '#2260FF',
  SIGNUP_BUTTON_COLOR: '#CAD6FF',
  STATUS_BAR_COLOR: '#E2EAFF',
  BLACK: '#000000',
  TEXT_INPUT_COLOR:'#ECF1FF',
  PLACEHOLDER_COLOR:'#809CFF'
};
